-- SPDX-License-Identifier: Apache-2.0
-- Licensed to the Ed-Fi Alliance under one or more agreements.
-- The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
-- See the LICENSE and NOTICES files in the project root for more information.

CREATE TABLE Aliases (
  Id BIGINT GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1),
  ReferentialPartitionKey SMALLINT NOT NULL,
  ReferentialId UUID NOT NULL,
  DocumentId BIGINT NOT NULL,
  DocumentPartitionKey SMALLINT NOT NULL,
  PRIMARY KEY (ReferentialPartitionKey, Id)
) PARTITION BY HASH(ReferentialPartitionKey);

CREATE TABLE Aliases_00 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 0);
CREATE TABLE Aliases_01 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 1);
CREATE TABLE Aliases_02 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 2);
CREATE TABLE Aliases_03 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 3);
CREATE TABLE Aliases_04 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 4);
CREATE TABLE Aliases_05 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 5);
CREATE TABLE Aliases_06 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 6);
CREATE TABLE Aliases_07 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 7);
CREATE TABLE Aliases_08 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 8);
CREATE TABLE Aliases_09 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 9);
CREATE TABLE Aliases_10 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 10);
CREATE TABLE Aliases_11 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 11);
CREATE TABLE Aliases_12 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 12);
CREATE TABLE Aliases_13 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 13);
CREATE TABLE Aliases_14 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 14);
CREATE TABLE Aliases_15 PARTITION OF Aliases FOR VALUES WITH (MODULUS 16, REMAINDER 15);

-- Referential ID uniqueness validation and reference insert into References support
CREATE UNIQUE INDEX UX_Aliases_ReferentialId ON Aliases(ReferentialPartitionKey, ReferentialId)
