services:
  # Kafka UI https://docs.kafka-ui.provectus.io/
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - ${KAFKA_UI_PORT:-8088}:8080
    depends_on:
      - kafka
    links:
      - kafka
      - kafka-postgresql-source
      - kafka-opensearch-sink
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka1
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0@sha256:b7c26c60bfafcbb90c538316570b84bab85f5dc82339aa7feefc3014274c689e
    container_name: dms-opensearch-dashboards
    ports:
      - ${OPENSEARCH_DASHBOARD_PORT:-5601}:5601
    expose:
      - ${OPENSEARCH_DASHBOARD_PORT:-5601}
    environment:
      OPENSEARCH_HOSTS: '["http://dms-opensearch:9200"]'
       # disables security dashboards plugin in OpenSearch Dashboards, otherwise will have TLS errors
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    restart: unless-stopped
