# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  kafka:
    image: apache/kafka:3.9.0@sha256:fbc7d7c428e3755cf36518d4976596002477e4c052d1f80b5b9eafd06d0fff2f
    container_name: dms-kafka1
    volumes:
      - kafka-data:/kafka/data
      - kafka-logs:/kafka/logs
    restart: unless-stopped
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server dms-kafka1:9092 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://dms-kafka1:9092
      KAFKA_LISTENERS: PLAINTEXT://dms-kafka1:9092,CONTROLLER://dms-kafka1:9093
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@dms-kafka1:9093
      # Default values for the following environment variables:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1
    ports:
      - '127.0.0.1:${KAFKA_PORT:-9092}:9092'
    networks:
      - dms
    hostname: dms-kafka1

  kafka-postgresql-source:
    image: edfialliance/ed-fi-kafka-connect:pre
    container_name: kafka-postgresql-source
    volumes:
      - kafka-postgresql-source-logs:/kafka/logs
      - kafka-postgresql-source-config:/kafka/config
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: dms-kafka1:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_source_config
      OFFSET_STORAGE_TOPIC: debezium_source_offset
      STATUS_STORAGE_TOPIC: debezium_source_status
    ports:
      - '127.0.0.1:${CONNECT_SOURCE_PORT:-8083}:8083'
    networks:
      - dms
    hostname: kafka-postgresql-source

networks:
  dms:
    external: true

volumes:
  kafka-data:
  kafka-logs:
  kafka-postgresql-source-logs:
  kafka-postgresql-source-config:
