# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  kafka:
    extends:
      file: kafka-broker.yml
      service: kafka

  kafka-postgresql-source:
    image: edfialliance/ed-fi-kafka-connect:pre
    container_name: kafka-postgresql-source
    volumes:
      - kafka-postgresql-source-logs:/kafka/logs
      - kafka-postgresql-source-config:/kafka/config
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: dms-kafka1:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_source_config
      OFFSET_STORAGE_TOPIC: debezium_source_offset
      STATUS_STORAGE_TOPIC: debezium_source_status
    ports:
      - '127.0.0.1:${CONNECT_SOURCE_PORT:-8083}:8083'
    networks:
      - dms
    hostname: kafka-postgresql-source
    logging:
      driver: json-file
      options:
        max-size: "${DOCKER_LOG_MAX_SIZE:-50m}"
        max-file: "${DOCKER_LOG_MAX_FILE:-5}"

networks:
  dms:
    external: true

volumes:
  kafka-data:
  kafka-logs:
  kafka-postgresql-source-logs:
  kafka-postgresql-source-config:
