# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dms-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-abcdefgh1!}
    ports:
      - '127.0.0.1:${MSSQL_PORT:-1435}:1433'
    volumes:
      - dms-mssql:/var/opt/mssql
    networks:
      - dms
    restart: always
    hostname: dms-mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"$$MSSQL_SA_PASSWORD\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

networks:
  dms:
    external: true

volumes:
  dms-mssql:
