events {
    worker_connections 1024;
}

http {
    server {
        listen 8080;
        server_name localhost dms-keycloak;

        location / {
            proxy_pass http://localhost:8080;
        }

        # Proxy for Keycloak (mapped as 8065:8080 on Docker)
        location /realms/edfi/protocol/openid-connect/token {
            proxy_pass http://dms-keycloak;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port 8080;
        }
    }
}
