# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  db:
    mem_limit: ${POSTGRES_CONTAINER_MEMORY:-10g}
    memswap_limit: ${POSTGRES_CONTAINER_MEMORY:-10g}
    tmpfs:
      - /var/lib/postgresql/data:rw,size=${POSTGRES_TMPFS_SIZE:-4g},mode=0700
    volumes: !override
      - ./postgresql-init.sh:/docker-entrypoint-initdb.d/postgresql-init.sh
