# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  config:
    image: edfialliance/dms-configuration-service:${DMS_IMAGE_TAG:-pre}
    container_name: dms-config-service
    environment:
      ASPNETCORE_HTTP_PORTS: ${DMS_CONFIG_ASPNETCORE_HTTP_PORTS:-8081}
      AppSettings__Datastore: ${DMS_CONFIG_DATASTORE:-postgresql}
      DatabaseSettings__DatabaseConnection: ${DMS_CONFIG_DATABASE_CONNECTION_STRING:-host=dms-postgresql;port=5432;username=postgres;password=${POSTGRES_PASSWORD};database=edfi_configurationservice;}
      DatabaseSettings__DatabaseEncryptionKey: ${DMS_CONFIG_DATABASE_ENCRYPTION_KEY:-}
      IdentitySettings__AllowRegistration: ${DMS_CONFIG_IDENTITY_ALLOW_REGISTRATION:-false}
      IdentitySettings__ConfigServiceRole: ${DMS_CONFIG_IDENTITY_SERVICE_ROLE:-cms-client}
      IdentitySettings__ClientRole: ${DMS_CONFIG_IDENTITY_CLIENT_ROLE:-dms-client}
      IdentitySettings__Authority: ${DMS_CONFIG_IDENTITY_AUTHORITY:-http://localhost:8045/realms/edfi}
      IdentitySettings__Audience: ${DMS_CONFIG_IDENTITY_AUDIENCE:-account}
      IdentitySettings__ClientId: ${DMS_CONFIG_IDENTITY_CLIENT_ID:-DmsConfigurationService}
      IdentitySettings__ClientSecret: ${DMS_CONFIG_IDENTITY_CLIENT_SECRET}
      IdentitySettings__RequireHttpsMetadata: ${DMS_CONFIG_IDENTITY_REQUIRE_HTTPS:-false}
      IdentitySettings__RoleClaimType: ${DMS_CONFIG_IDENTITY_ROLE_CLAIM_TYPE:-http://schemas.microsoft.com/ws/2008/06/identity/claims/role}
      Serilog__MinimumLevel__Default: ${DMS_CONFIG_LOG_LEVEL:-Information}
      AppSettings__DeployDatabaseOnStartup: ${DMS_CONFIG_DEPLOY_DATABASE:-true}
      AppSettings__TokenRequestTimeoutSeconds: ${DMS_CONFIG_TOKEN_TIMEOUT_SECONDS:-30}
      AppSettings__IdentityProvider: ${DMS_CONFIG_IDENTITY_PROVIDER:-keycloak}
      # Segment of the url to use as base for all request. The default path base is deliberately blank on the following line
      AppSettings__PathBase: ${DMS_CONFIG_PATH_BASE:-}
      AppSettings__UseReverseProxyHeaders: ${DMS_CONFIG_USE_REVERSE_PROXY_HEADERS:-false}
      ClaimsOptions__ClaimsSource: ${DMS_CONFIG_CLAIMS_SOURCE:-Embedded}
      ClaimsOptions__DangerouslyEnableUnrestrictedClaimsLoading: ${DMS_CONFIG_DANGEROUSLY_ENABLE_UNRESTRICTED_CLAIMS_LOADING:-false}
      ClaimsOptions__ClaimsDirectory: ${DMS_CONFIG_CLAIMS_DIRECTORY:-}
      IdentitySettings__EncryptionKey: ${DMS_CONFIG_IDENTITY_ENCRYPTION_KEY:-}
      Cors__SwaggerUIOrigin: ${DMS_SWAGGER_UI_URL:-http://localhost:8082}
    ports:
      - '127.0.0.1:${DMS_CONFIG_ASPNETCORE_HTTP_PORTS:-8081}:${DMS_CONFIG_ASPNETCORE_HTTP_PORTS:-8081}'
    volumes:
      - ../../src/config/backend/EdFi.DmsConfigurationService.Backend/Deploy/AdditionalClaimsets:/app/additional-claims
    networks:
      - dms
    restart: unless-stopped
    healthcheck:
      test: curl -s http://localhost:8081/health >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
    hostname: config

networks:
  dms:
    external: true
