# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

services:
  swagger-ui:
    image: nginx:alpine
    container_name: dms-swagger-ui
    ports:
      - "${DMS_SWAGGER_UI_PORT:-8082}:80"
    environment:
      - DMS_HTTP_PORTS=${DMS_HTTP_PORTS:-8080}
    volumes:
      - ./custom-swagger-ui:/usr/share/nginx/html:ro
    networks:
      - dms

networks:
  dms:
    external: true
