/*
 * SPDX-License-Identifier: Apache-2.0
 * Licensed to the Ed-Fi Alliance under one or more agreements.
 * The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
 * See the LICENSE and NOTICES files in the project root for more information.
 */

# Relational Authorization Demo
#
# This demo is based on recent authorization work in:
# reference/design/backend-redesign/epics/14-authorization/EPIC.md
#
# Start the relational E2E Docker environment before using this file, then run this
# provision-only command from the repository root:
#
# pwsh -NoProfile -Command "./eng/docker-compose/provision-relational-e2e-database.ps1 -EnvironmentFile './eng/docker-compose/.env.e2e.relational' -Configuration Release; docker restart dms-local-dms-1"
#
# The DMS instance below intentionally points to edfi_datamanagementservice_relational.
# Run this file once against that freshly provisioned relational database. Before rerunning,
# provision again because this file uses fixed demo IDs and captured Location headers.

@configPort=8081
@dmsPort=8080
@dmsInstanceDatabase=edfi_datamanagementservice_relational
# RestClient runs on the host, where Docker service names like dms-config-service do not resolve.
@tokenUrl=http://localhost:{{configPort}}/connect/token

@sysAdminId=sys-admin
@sysAdminSecret=SdfH)98&JkSdfH)98&JkSdfH)98&JkSdfH)9
@encodedSysAdminSecret=SdfH%2998%26JkSdfH%2998%26JkSdfH%2998%26JkSdfH)9

#
# Preparation: CMS administrator, discovery, DMS instance, clients, and tokens.
# Run this preparation block before the live demo.
#

### Register the system administrator credentials
# If this administrator already exists, continue with the token request.
POST http://localhost:{{configPort}}/connect/register
Content-Type: application/x-www-form-urlencoded

ClientId={{sysAdminId}}
&ClientSecret={{encodedSysAdminSecret}}
&DisplayName=System Administrator

### Create a CMS administrator token
# @name configTokenRequest
POST http://localhost:{{configPort}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{sysAdminId}}
&client_secret={{encodedSysAdminSecret}}
&grant_type=client_credentials
&scope=edfi_admin_api/full_access

###
@configToken={{configTokenRequest.response.body.access_token}}

### Read the DMS discovery document
# @name discovery
GET http://localhost:{{dmsPort}}

###
@dataApi={{discovery.response.body.urls.dataManagementApi}}
@tokenInfoUrl={{discovery.response.body.urls.tokenInfo}}

### Create the relational DMS instance used by all demo applications
# @name createDmsInstance
POST http://localhost:{{configPort}}/v2/dmsInstances
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "instanceType": "Test",
    "instanceName": "Authorization Relational Demo",
    "connectionString": "host=dms-postgresql;port=5432;username=postgres;password=abcdefgh1!;database={{dmsInstanceDatabase}};"
}

###
@dmsInstanceId={{createDmsInstance.response.body.id}}

### Create the Ed-Fi and TPDM namespace vendor for EdOrg and people tokens
# @name createEdFiVendor
POST http://localhost:{{configPort}}/v2/vendors
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "company": "Authorization Demo Ed-Fi Vendor",
    "contactName": "Authorization Demo",
    "contactEmailAddress": "authorization-demo-edfi@example.com",
    "namespacePrefixes": "uri://ed-fi.org,uri://tpdm.ed-fi.org"
}

###
@edFiVendorLocation={{createEdFiVendor.response.headers.location}}

### Retrieve the Ed-Fi vendor id
# @name getEdFiVendor
GET {{edFiVendorLocation}}
Authorization: bearer {{configToken}}

###
@edFiVendorId={{getEdFiVendor.response.body.id}}

### Create the ns2 namespace vendor
# @name createNs2Vendor
POST http://localhost:{{configPort}}/v2/vendors
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "company": "Authorization Demo NS2 Vendor",
    "contactName": "Authorization Demo",
    "contactEmailAddress": "authorization-demo-ns2@example.com",
    "namespacePrefixes": "uri://ns2.org"
}

###
@ns2VendorLocation={{createNs2Vendor.response.headers.location}}

### Retrieve the ns2 vendor id
# @name getNs2Vendor
GET {{ns2VendorLocation}}
Authorization: bearer {{configToken}}

###
@ns2VendorId={{getNs2Vendor.response.body.id}}

### Create the ns3 namespace vendor
# @name createNs3Vendor
POST http://localhost:{{configPort}}/v2/vendors
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "company": "Authorization Demo NS3 Vendor",
    "contactName": "Authorization Demo",
    "contactEmailAddress": "authorization-demo-ns3@example.com",
    "namespacePrefixes": "uri://ns3.org"
}

###
@ns3VendorLocation={{createNs3Vendor.response.headers.location}}

### Retrieve the ns3 vendor id
# @name getNs3Vendor
GET {{ns3VendorLocation}}
Authorization: bearer {{configToken}}

###
@ns3VendorId={{getNs3Vendor.response.body.id}}

### Create seed application: broad setup token for EdOrg-only data
# @name createSeedApplication
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{edFiVendorId}},
    "applicationName": "Authorization Demo Seed",
    "claimSetName": "E2E-RelationshipsWithEdOrgsOnlyClaimSet",
    "educationOrganizationIds": [2, 201, 20101, 3, 301, 30101, 255901001, 255901222],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@seedClientKey={{createSeedApplication.response.body.key}}
@seedClientSecret={{createSeedApplication.response.body.secret}}

### Create school-only application: authorized only for school 255901001
# @name createSchoolOnlyApplication
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{edFiVendorId}},
    "applicationName": "Authorization Demo School Only",
    "claimSetName": "E2E-RelationshipsWithEdOrgsOnlyClaimSet",
    "educationOrganizationIds": [255901001],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@schoolOnlyClientKey={{createSchoolOnlyApplication.response.body.key}}
@schoolOnlyClientSecret={{createSchoolOnlyApplication.response.body.secret}}

### Create wrong-school application: authorized only for school 255901222
# @name createWrongSchoolApplication
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{edFiVendorId}},
    "applicationName": "Authorization Demo Wrong School",
    "claimSetName": "E2E-RelationshipsWithEdOrgsOnlyClaimSet",
    "educationOrganizationIds": [255901222],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@wrongSchoolClientKey={{createWrongSchoolApplication.response.body.key}}
@wrongSchoolClientSecret={{createWrongSchoolApplication.response.body.secret}}

### Create combined-strategy application: State 2 plus School 30101
# @name createOrInvertedApplication
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{edFiVendorId}},
    "applicationName": "Authorization Demo OR Inverted",
    "claimSetName": "E2E-RelationshipsWithEdOrgsOnlyOrInvertedClaimSet",
    "educationOrganizationIds": [2, 30101],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@orInvertedClientKey={{createOrInvertedApplication.response.body.key}}
@orInvertedClientSecret={{createOrInvertedApplication.response.body.secret}}

### Create people application: EdFiSandbox with State 3 and LEA 6255901
# @name createPeopleApplication
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{edFiVendorId}},
    "applicationName": "Authorization Demo People",
    "claimSetName": "EdFiSandbox",
    "educationOrganizationIds": [3, 6255901],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@peopleClientKey={{createPeopleApplication.response.body.key}}
@peopleClientSecret={{createPeopleApplication.response.body.secret}}

### Create namespace ns2 application
# @name createNs2Application
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{ns2VendorId}},
    "applicationName": "Authorization Demo Namespace NS2",
    "claimSetName": "E2E-NameSpaceBasedClaimSet",
    "educationOrganizationIds": [],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@ns2ClientKey={{createNs2Application.response.body.key}}
@ns2ClientSecret={{createNs2Application.response.body.secret}}

### Create namespace ns3 application
# @name createNs3Application
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{ns3VendorId}},
    "applicationName": "Authorization Demo Namespace NS3",
    "claimSetName": "E2E-NameSpaceBasedClaimSet",
    "educationOrganizationIds": [],
    "dmsInstanceIds": [{{dmsInstanceId}}]
}

###
@ns3ClientKey={{createNs3Application.response.body.key}}
@ns3ClientSecret={{createNs3Application.response.body.secret}}

### Refresh DMS claim-set metadata before creating demo tokens
POST http://localhost:{{dmsPort}}/management/reload-claimsets
Content-Type: application/json
Authorization: bearer {{configToken}}

{}

### Create seedToken
# @name seedTokenRequest
POST {{tokenUrl}}
Authorization: basic {{seedClientKey}}:{{seedClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@seedToken={{seedTokenRequest.response.body.access_token}}

### Create schoolOnlyToken
# @name schoolOnlyTokenRequest
POST {{tokenUrl}}
Authorization: basic {{schoolOnlyClientKey}}:{{schoolOnlyClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@schoolOnlyToken={{schoolOnlyTokenRequest.response.body.access_token}}

### Create wrongSchoolToken
# @name wrongSchoolTokenRequest
POST {{tokenUrl}}
Authorization: basic {{wrongSchoolClientKey}}:{{wrongSchoolClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@wrongSchoolToken={{wrongSchoolTokenRequest.response.body.access_token}}

### Create orInvertedToken
# @name orInvertedTokenRequest
POST {{tokenUrl}}
Authorization: basic {{orInvertedClientKey}}:{{orInvertedClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@orInvertedToken={{orInvertedTokenRequest.response.body.access_token}}

### Create peopleToken
# @name peopleTokenRequest
POST {{tokenUrl}}
Authorization: basic {{peopleClientKey}}:{{peopleClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@peopleToken={{peopleTokenRequest.response.body.access_token}}

### Create namespaceNs2Token
# @name namespaceNs2TokenRequest
POST {{tokenUrl}}
Authorization: basic {{ns2ClientKey}}:{{ns2ClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@namespaceNs2Token={{namespaceNs2TokenRequest.response.body.access_token}}

### Create namespaceNs3Token
# @name namespaceNs3TokenRequest
POST {{tokenUrl}}
Authorization: basic {{ns3ClientKey}}:{{ns3ClientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@namespaceNs3Token={{namespaceNs3TokenRequest.response.body.access_token}}

#
# Preparation: dependency descriptors and demo data.
#

### Seed EdOrg and school descriptors
POST {{dataApi}}/ed-fi/educationOrganizationCategoryDescriptors
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "namespace": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor",
    "codeValue": "State",
    "description": "State",
    "shortDescription": "State"
}

### Seed EdOrg and school descriptors
POST {{dataApi}}/ed-fi/educationOrganizationCategoryDescriptors
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "namespace": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor",
    "codeValue": "District",
    "description": "District",
    "shortDescription": "District"
}

### Seed EdOrg and school descriptors
POST {{dataApi}}/ed-fi/educationOrganizationCategoryDescriptors
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "namespace": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor",
    "codeValue": "School",
    "description": "School",
    "shortDescription": "School"
}

### Seed people EdOrg descriptors
POST {{dataApi}}/ed-fi/educationOrganizationCategoryDescriptors
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor",
    "codeValue": "District",
    "description": "District",
    "shortDescription": "District"
}

### Seed people EdOrg descriptors
POST {{dataApi}}/ed-fi/educationOrganizationCategoryDescriptors
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor",
    "codeValue": "school",
    "description": "school",
    "shortDescription": "school"
}

### Seed grade-level descriptor
POST {{dataApi}}/ed-fi/gradeLevelDescriptors
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/GradeLevelDescriptor",
    "codeValue": "Tenth Grade",
    "description": "Tenth Grade",
    "shortDescription": "Tenth Grade"
}

### Seed LEA category descriptor
POST {{dataApi}}/ed-fi/localEducationAgencyCategoryDescriptors
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor",
    "codeValue": "ABC",
    "description": "ABC",
    "shortDescription": "ABC"
}

### Seed exit-withdraw descriptor for StudentSchoolAssociation
POST {{dataApi}}/ed-fi/exitWithdrawTypeDescriptors
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/ExitWithdrawTypeDescriptor",
    "codeValue": "Student withdrew",
    "description": "Student withdrew",
    "shortDescription": "Student withdrew"
}

### Seed post-secondary event category descriptor
POST {{dataApi}}/ed-fi/postSecondaryEventCategoryDescriptors
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/PostSecondaryEventCategoryDescriptor",
    "codeValue": "College Application",
    "description": "College Application",
    "shortDescription": "College Application"
}

### Seed Section 2 schools: one authorized, one unauthorized for schoolOnlyToken
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "schoolId": 255901001,
    "nameOfInstitution": "Authorized school one",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade"
        }
    ]
}

### Seed Section 2 schools: one authorized, one unauthorized for schoolOnlyToken
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "schoolId": 255901222,
    "nameOfInstitution": "Unauthorized school",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade"
        }
    ]
}

### Seed unauthorized academic week
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "weekIdentifier": "week unauth",
    "schoolReference": {
        "schoolId": 255901222
    },
    "beginDate": "2023-08-01",
    "endDate": "2023-08-07",
    "totalInstructionalDays": 5
}

### Seed authorized academic week 1
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "weekIdentifier": "week auth 1",
    "schoolReference": {
        "schoolId": 255901001
    },
    "beginDate": "2023-08-08",
    "endDate": "2023-08-14",
    "totalInstructionalDays": 5
}

### Seed authorized academic week 2
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "weekIdentifier": "week auth 2",
    "schoolReference": {
        "schoolId": 255901001
    },
    "beginDate": "2023-08-15",
    "endDate": "2023-08-21",
    "totalInstructionalDays": 4
}

### Seed Section 4 hierarchy: State 2
POST {{dataApi}}/ed-fi/stateEducationAgencies
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "stateEducationAgencyId": 2,
    "nameOfInstitution": "Demo State 2",
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#State"
        }
    ]
}

### Seed Section 4 hierarchy: State 3
POST {{dataApi}}/ed-fi/stateEducationAgencies
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "stateEducationAgencyId": 3,
    "nameOfInstitution": "Demo State 3",
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#State"
        }
    ]
}

### Seed Section 4 hierarchy: LEA 201 under State 2
POST {{dataApi}}/ed-fi/localEducationAgencies
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "localEducationAgencyId": 201,
    "nameOfInstitution": "Test LEA 201",
    "stateEducationAgencyReference": {
        "stateEducationAgencyId": 2
    },
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#District"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor#ABC"
}

### Seed Section 4 hierarchy: LEA 301 under State 3
POST {{dataApi}}/ed-fi/localEducationAgencies
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "localEducationAgencyId": 301,
    "nameOfInstitution": "Test LEA 301",
    "stateEducationAgencyReference": {
        "stateEducationAgencyId": 3
    },
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#District"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor#ABC"
}

### Seed Section 4 hierarchy: School 20101 under LEA 201
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "schoolId": 20101,
    "nameOfInstitution": "Test school 20101",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade"
        }
    ],
    "localEducationAgencyReference": {
        "localEducationAgencyId": 201
    }
}

### Seed Section 4 hierarchy: School 30101 under LEA 301
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{seedToken}}
Content-Type: application/json

{
    "schoolId": 30101,
    "nameOfInstitution": "Test school 30101",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://tpdm.ed-fi.org/EducationOrganizationCategoryDescriptor#School"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade"
        }
    ],
    "localEducationAgencyReference": {
        "localEducationAgencyId": 301
    }
}

### Seed Section 5 people hierarchy: LEA 6255901 under existing State 3
POST {{dataApi}}/ed-fi/localEducationAgencies
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "localEducationAgencyId": 6255901,
    "nameOfInstitution": "People Demo LEA",
    "stateEducationAgencyReference": {
        "stateEducationAgencyId": 3
    },
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#District"
        }
    ],
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor#ABC"
}

### Seed Section 5 people hierarchy: School 6255901001
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "schoolId": 6255901001,
    "nameOfInstitution": "People Demo School",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/EducationOrganizationCategoryDescriptor#school"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade"
        }
    ],
    "localEducationAgencyReference": {
        "localEducationAgencyId": 6255901
    }
}

### Seed Section 5 student 61
POST {{dataApi}}/ed-fi/students
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "studentUniqueId": "61",
    "firstName": "student-fn",
    "lastSurname": "student-ln",
    "birthDate": "2008-01-01"
}

### Seed Section 5 StudentSchoolAssociation: Student 61 to School 6255901001
# @name createPeopleStudentSchoolAssociation
POST {{dataApi}}/ed-fi/studentSchoolAssociations
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "studentReference": {
        "studentUniqueId": "61"
    },
    "schoolReference": {
        "schoolId": 6255901001
    },
    "entryGradeLevelDescriptor": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade",
    "entryDate": "2023-08-01",
    "exitGradeLevel": "uri://ed-fi.org/GradeLevelDescriptor#Tenth Grade",
    "exitWithdrawTypeDescriptor": "uri://ed-fi.org/ExitWithdrawTypeDescriptor#Student withdrew"
}

###
@studentSchoolAssociationLocation={{createPeopleStudentSchoolAssociation.response.headers.location}}

### Capture StudentSchoolAssociation id for the live delete step
# @name getPeopleStudentSchoolAssociation
GET {{studentSchoolAssociationLocation}}
Authorization: bearer {{peopleToken}}

###
@studentSchoolAssociationId={{getPeopleStudentSchoolAssociation.response.body.id}}

### Seed Section 5 PostSecondaryEvent for Student 61
# @name createPeoplePostSecondaryEvent
POST {{dataApi}}/ed-fi/PostSecondaryEvents
Authorization: bearer {{peopleToken}}
Content-Type: application/json

{
    "eventDate": "2023-09-15",
    "postSecondaryEventCategoryDescriptor": "uri://ed-fi.org/PostSecondaryEventCategoryDescriptor#College Application",
    "studentReference": {
        "studentUniqueId": "61"
    }
}

###
@postSecondaryEventLocation={{createPeoplePostSecondaryEvent.response.headers.location}}

### Capture PostSecondaryEvent id for the live people relationship demo
# @name getPeoplePostSecondaryEvent
GET {{postSecondaryEventLocation}}
Authorization: bearer {{peopleToken}}

###
@postSecondaryEventId={{getPeoplePostSecondaryEvent.response.body.id}}

#
# Live demo starts here.
#

#
# Section 1: Token Context
#

### Token info: show claim_set, education_organizations, and namespace_prefixes
# Expected: 200. Useful fields: claim_set, education_organizations, namespace_prefixes.
# @name tokenInfoForSchoolOnly
POST {{tokenInfoUrl}}
Authorization: bearer {{schoolOnlyToken}}
Content-Type: application/json

{
    "token": "{{schoolOnlyToken}}"
}

#
# Section 2: EdOrg Filtering And Total Count
#

### Authorized academic week query with post-authorization paging and count
# Expected: 200, Total-Count: 2, body contains one authorized week because limit=1.
# The week for school 255901222 is filtered out before paging/count.
GET {{dataApi}}/ed-fi/academicWeeks?totalCount=true&limit=1
Authorization: bearer {{schoolOnlyToken}}

#
# Section 3: EdOrg Write Denial
#

### Try to create an academic week for school 255901001 using a token for school 255901222
# Expected: 403 Authorization Denied.
# Error should mention no relationship between EdOrg claim 255901222 and resource item's SchoolId.
# @name forbiddenAcademicWeekCreate
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{wrongSchoolToken}}
Content-Type: application/json

{
    "weekIdentifier": "post create forbidden",
    "schoolReference": {
        "schoolId": 255901001
    },
    "beginDate": "2023-08-08",
    "endDate": "2023-08-14",
    "totalInstructionalDays": 5
}

### Prove the denied POST did not create a record
# Expected: 200, Total-Count: 0, body [].
GET {{dataApi}}/ed-fi/academicWeeks?weekIdentifier=post%20create%20forbidden&totalCount=true
Authorization: bearer {{schoolOnlyToken}}

#
# Section 4: Combined Authorization Strategies
#

### GET-many with compatible normal and inverted EdOrg strategies ORed together
# Expected: 200, returns LEA 201 and LEA 301.
# LEA 201 is authorized top-down from State 2.
# LEA 301 is authorized bottom-up from School 30101.
GET {{dataApi}}/ed-fi/localEducationAgencies
Authorization: bearer {{orInvertedToken}}

#
# Section 5: People Relationship Delete Demo
#

### Before removing the relationship, the PostSecondaryEvent is readable
# Expected: 200.
GET {{dataApi}}/ed-fi/PostSecondaryEvents/{{postSecondaryEventId}}
Authorization: bearer {{peopleToken}}

### Remove the StudentSchoolAssociation relationship
# Expected: 204.
DELETE {{dataApi}}/ed-fi/studentSchoolAssociations/{{studentSchoolAssociationId}}
Authorization: bearer {{peopleToken}}

### The resource still exists, but the caller no longer has a student relationship path
# Expected: 403 Authorization Denied.
GET {{dataApi}}/ed-fi/PostSecondaryEvents/{{postSecondaryEventId}}
Authorization: bearer {{peopleToken}}

### Delete is denied for the same reason
# Expected: 403 Authorization Denied.
DELETE {{dataApi}}/ed-fi/PostSecondaryEvents/{{postSecondaryEventId}}
Authorization: bearer {{peopleToken}}

#
# Section 6: Namespace Authorization
#

### Create a descriptor in uri://ns2.org with the ns2 token
# Expected: 200 or 201.
# @name createNamespaceDescriptor
POST {{dataApi}}/ed-fi/absenceEventCategoryDescriptors
Authorization: bearer {{namespaceNs2Token}}
Content-Type: application/json

{
    "codeValue": "Namespace Based",
    "description": "Namespace Based",
    "effectiveBeginDate": "2024-05-14",
    "effectiveEndDate": "2024-05-14",
    "namespace": "uri://ns2.org/AbsenceEventCategoryDescriptor",
    "shortDescription": "Namespace Based"
}

###
@namespaceDescriptorLocation={{createNamespaceDescriptor.response.headers.location}}

### Capture the ns2 descriptor id
# @name getNamespaceDescriptorAsNs2
GET {{namespaceDescriptorLocation}}
Authorization: bearer {{namespaceNs2Token}}

###
@descriptorId={{getNamespaceDescriptorAsNs2.response.body.id}}

### A token limited to uri://ns3.org cannot read the ns2 descriptor by id
# Expected: 403 Authorization Denied.
GET {{dataApi}}/ed-fi/absenceEventCategoryDescriptors/{{descriptorId}}
Authorization: bearer {{namespaceNs3Token}}

### Query behavior filters unauthorized namespace data out of the result set
# Expected: 200 with [].
GET {{dataApi}}/ed-fi/absenceEventCategoryDescriptors?codeValue=Namespace%20Based
Authorization: bearer {{namespaceNs3Token}}
