### DMS Auth Via Docker
POST http://localhost:8080/oauth/token

Content-Type: "application/json"
{
    "clientId": "ClientId",
    "clientSecret": "ClientSecret123#"
}

###
### DMS Auth running locally Proper
POST http://localhost:5198/oauth/token
Authorization: Basic CSClientApp:test1@Secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
### Wrong Authorization Headings
POST http://localhost:5198/oauth/token
Authorization: clientId:clientSecret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
### Missing Authorization Headings
POST http://localhost:5198/oauth/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
### Proper body
POST http://localhost:5198/oauth/token
Authorization: Basic CSClientApp:test1@Secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
### Keycloak as a service
POST http://localhost:8045/realms/edfi/protocol/openid-connect/token
Authorization: Basic CSClientApp:test1@Secret
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
