<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ed-fi.org/6.1.0" xmlns:ann="http://ed-fi.org/annotation" targetNamespace="http://ed-fi.org/6.1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:include schemaLocation="Ed-Fi-Core.xsd" />
  <xs:annotation>
    <xs:documentation>===== Ed-Fi 6.1.0 Extensions =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== Domain Entities =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== Descriptors =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-HairColorDescriptor">
    <xs:annotation>
      <xs:documentation>This descriptor defines student hair color.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Descriptor</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="DescriptorType" />
    </xs:complexContent>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Associations =====</xs:documentation>
  </xs:annotation>
  <xs:complexType name="EXTENSION-StudentEducationOrganizationAssociationExtension">
    <xs:annotation>
      <xs:documentation></xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Association</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="StudentEducationOrganizationAssociation">
        <xs:sequence>
          <xs:element name="HairColor" type="EXTENSION-HairColorDescriptorReferenceType" minOccurs="0">
            <xs:annotation>
              <xs:documentation>hair color of student</xs:documentation>
              <xs:appinfo>
                <ann:Descriptor>EXTENSION-HairColorDescriptor</ann:Descriptor>
              </xs:appinfo>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:annotation>
    <xs:documentation>===== Extended Reference Types =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== Extended Descriptor Reference Types =====</xs:documentation>
  </xs:annotation>
  <xs:simpleType name="EXTENSION-HairColorDescriptorReferenceType">
    <xs:annotation>
      <xs:documentation>This descriptor defines student hair color.</xs:documentation>
      <xs:appinfo>
        <ann:TypeGroup>Extended Descriptor Reference</ann:TypeGroup>
      </xs:appinfo>
    </xs:annotation>
    <xs:restriction base="DescriptorReferenceType" />
  </xs:simpleType>
  <xs:annotation>
    <xs:documentation>===== Common Types =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== Enumerations and Enumerated Collections =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== String Simple Types =====</xs:documentation>
  </xs:annotation>
  <xs:annotation>
    <xs:documentation>===== Numeric Simple Types =====</xs:documentation>
  </xs:annotation>
</xs:schema>
