// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

namespace EdFi.DataManagementService.Backend.Postgresql.Model;

/// <summary>
/// A row from the Aliases table
/// </summary>
public record Alias(
    /// <summary>
    /// The partition key for this Alias
    /// </summary>
    int ReferentialPartitionKey,
    /// <summary>
    /// The ReferentialId for this Alias
    /// </summary>
    Guid ReferentialId,
    /// <summary>
    /// The Id of the Document represented by this Alias
    /// </summary>
    long DocumentId,
    /// <summary>
    /// The DocumentPartitionKey of the Document represented by this Alias
    /// </summary>
    int DocumentPartitionKey,
    /// <summary>
    /// The autogenerated Id
    /// </summary>
    long? Id = null
);
