# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

version: '3'
services:
  db:
    container_name: Postgres-DMS
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_ADMIN_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_ADMIN_PASSWORD:-P@ssW0rd}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - dms-pgsql:/var/lib/postgresql/data
volumes:
  dms-pgsql:
    driver: local

networks:
  dms-net:
    external: true
