// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

using System.Globalization;
using Microsoft.Extensions.Options;

namespace EdFi.DataManagementService.Frontend.AspNetCore.Configuration;

public class AppSettings
{
    public const int BytesPerMegabyte = 1024 * 1024;
    public const int DefaultMaxRequestBodySizeMegabytes = 10;
    public const int DefaultCorrelationIdMaxLength = 255;

    /// <summary>
    /// Smallest value <c>CorrelationIdMaxLength</c> may be configured to, inclusive.
    /// 64 is the shortest cap that preserves every common upstream correlation ID scheme
    /// intact - the longest of them, a full W3C <c>traceparent</c>, is 55 characters, and the
    /// server-generated Kestrel <c>HttpContext.TraceIdentifier</c> that DMS falls back to is 22.
    /// A cap below this would silently truncate real identifiers, including DMS's own, which
    /// would collapse every request on one connection onto a single correlation ID.
    /// See reference/adr-correlation-id-normalization.md.
    /// </summary>
    public const int MinimumCorrelationIdMaxLength = 64;

    /// <summary>
    /// Largest value <c>CorrelationIdMaxLength</c> may be configured to, inclusive.
    /// 1024 is generous for any real identifier scheme while bounding how much client-controlled
    /// text a single request can push into every log event and error response body.
    /// </summary>
    public const int MaximumCorrelationIdMaxLength = 1024;

    public required string AuthenticationService { get; set; }
    public required string Datastore { get; set; }
    public int MaxRequestBodySizeMegabytes { get; set; } = DefaultMaxRequestBodySizeMegabytes;
    public string? StartupStatusFilePath { get; set; }
    public required string CorrelationIdHeader { get; set; }
    public string DomainsExcludedFromOpenApi { get; set; } = string.Empty;
    public string RouteQualifierSegments { get; set; } = string.Empty;

    /// <summary>
    /// Maximum allowed length of a correlation ID, whether it came from the client's
    /// Correlation ID header or was generated by the server, measured in UTF-16 code units
    /// rather than user-perceived characters. Values longer than this limit are truncated
    /// before sanitization and logging. Defaults to 255 and must be between
    /// <see cref="MinimumCorrelationIdMaxLength"/> and
    /// <see cref="MaximumCorrelationIdMaxLength"/> inclusive.
    /// </summary>
    public int CorrelationIdMaxLength { get; set; } = DefaultCorrelationIdMaxLength;

    /// <summary>
    /// When true, enables multi-tenancy mode where the tenant identifier is extracted from the URL route.
    /// </summary>
    public bool MultiTenancy { get; set; } = false;

    /// <summary>
    /// Gets the route qualifier segments as an array by splitting the comma-separated string.
    /// Returns empty array if RouteQualifierSegments is null or empty.
    /// </summary>
    public string[] GetRouteQualifierSegmentsArray() =>
        string.IsNullOrWhiteSpace(RouteQualifierSegments)
            ? []
            : RouteQualifierSegments.Split(
                ',',
                StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries
            );
}

public class AppSettingsValidator : IValidateOptions<AppSettings>
{
    public ValidateOptionsResult Validate(string? name, AppSettings options)
    {
        if (string.IsNullOrWhiteSpace(options.AuthenticationService))
        {
            return ValidateOptionsResult.Fail("Missing required AppSettings value: AuthenticationService");
        }

        if (string.IsNullOrWhiteSpace(options.Datastore))
        {
            return ValidateOptionsResult.Fail("Missing required AppSettings value: Datastore");
        }

        if (
            !options.Datastore.Equals("postgresql", StringComparison.CurrentCultureIgnoreCase)
            && !options.Datastore.Equals("mssql", StringComparison.CurrentCultureIgnoreCase)
        )
        {
            return ValidateOptionsResult.Fail(
                "AppSettings value Datastore must be one of: postgresql, mssql"
            );
        }

        if (options.MaxRequestBodySizeMegabytes <= 0)
        {
            return ValidateOptionsResult.Fail(
                "AppSettings value MaxRequestBodySizeMegabytes must be greater than 0"
            );
        }

        if (
            options.CorrelationIdMaxLength < AppSettings.MinimumCorrelationIdMaxLength
            || options.CorrelationIdMaxLength > AppSettings.MaximumCorrelationIdMaxLength
        )
        {
            // The message is brace-free on purpose. ReportInvalidConfigurationMiddleware passes
            // each failure straight to ILogger.LogCritical as the *message template* argument, and
            // Serilog re-reads that template from {OriginalFormat} and parses it, so a brace here
            // would be taken for a property hole rather than logged literally.
            return ValidateOptionsResult.Fail(
                "AppSettings value CorrelationIdMaxLength was "
                    + options.CorrelationIdMaxLength.ToString(CultureInfo.InvariantCulture)
                    + ", which is outside the permitted range of "
                    + AppSettings.MinimumCorrelationIdMaxLength.ToString(CultureInfo.InvariantCulture)
                    + " to "
                    + AppSettings.MaximumCorrelationIdMaxLength.ToString(CultureInfo.InvariantCulture)
                    + " inclusive"
            );
        }

        return ValidateOptionsResult.Success;
    }
}
