apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    serviceName: postgres
spec:
  selector:
    serviceName: postgres
  type: NodePort
  ports:
    - protocol: TCP
      port: 5402
      targetPort: 5432
      nodePort: 30000
