// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

using EdFi.DataManagementService.Core.External.Model;

namespace EdFi.DataManagementService.Core.Response;

/// <summary>
/// Provides human-readable summary of the failure responses
/// </summary>
internal record FailureResponse(
    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    string detail,
    /// <summary>
    /// A URI reference [RFC3986] that identifies the problem type. This specification encourages that, when
    /// dereferenced, it provide human-readable documentation for the problem type
    /// (e.g., using HTML [W3C.REC-html5-20141028]).  When this member is not present, its value is assumed to be
    /// "about:blank".
    /// </summary>
    string type,
    /// <summary>
    /// A short, human-readable summary of the problem type.It SHOULD NOT change from occurrence to occurrence
    /// of the problem, except for purposes of localization(e.g., using proactive content negotiation;
    /// see[RFC7231], Section 3.4).
    /// </summary>
    string title,
    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    int status,
    /// <summary>
    /// Gets or sets a correlation id that is logged with the details of the exception.
    /// </summary>
    string? correlationId,
    /// <summary>
    /// Contains arrays of validation errors keyed by JSON Path (intended for use by a domain expert).
    /// </summary>
    Dictionary<string, string[]>? validationErrors,
    /// <summary>
    /// Contains an array of error messages encountered while processing the request (intended for use by a technical audience).
    /// </summary>
    string[]? errors
)
{
    private static readonly string _typePrefix = "urn:ed-fi:api";
    private static readonly string _badRequestTypePrefix = $"{_typePrefix}:bad-request";
    private const string DataConflictTypePrefix = $"{_typePrefix}:data-conflict:dependent-item-exists";

    public static FailureResponse ForDataValidation(
        string detail,
        Dictionary<string, string[]>? validationErrors,
        string[]? errors
    ) =>
        new(
            detail,
            type: $"{_badRequestTypePrefix}:data",
            title: "Data Validation Failed",
            status: 400,
            correlationId: null,
            validationErrors,
            errors
        );

    public static FailureResponse ForBadRequest(
        string detail,
        Dictionary<string, string[]>? ValidationErrors,
        string[]? Errors
    ) =>
        new(
            detail,
            type: _badRequestTypePrefix,
            title: "Bad Request",
            status: 400,
            correlationId: null,
            validationErrors: ValidationErrors,
            errors: Errors
        );

    public static FailureResponse ForNotFound(string detail) =>
        new(
            detail,
            type: $"{_typePrefix}:not-found",
            title: "Not Found",
            status: 404,
            correlationId: null,
            validationErrors: null,
            errors: null
        );

    public static FailureResponse ForIdentityConflict(string[]? errors) =>
        new(
            detail: "The identifying value(s) of the item are the same as another item that already exists.",
            type: $"{_typePrefix}:identity-conflict",
            title: "Identifying Values Are Not Unique",
            status: 409,
            correlationId: null,
            validationErrors: null,
            errors
        );

    public static FailureResponse ForDataConflict(string dependentItemName)
    {
        dependentItemName = !string.IsNullOrEmpty(dependentItemName)
            ? $"'{dependentItemName}'"
            : string.Empty;

        return new(
            detail: $"The requested action cannot be performed because this item is referenced by an existing {dependentItemName} item.",
            type: $"{_typePrefix}:data-conflict:dependent-item-exists",
            title: "Dependent Item Exists",
            status: 409,
            correlationId: null,
            validationErrors: null,
            errors: null
        );
    }

    public static FailureResponse ForInvalidReferences(ResourceName[] resourceNames) =>
        new(
        var value = new List<string>
        {
            title: "Unresolved Reference",
            status: 409,
            errorDetail
            validationErrors: null,
            errors: null
        );
}
