# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

<#
.SYNOPSIS
    Asserts that build-dms.ps1's version stamping cannot reach src/plugins/Directory.Build.props.

.DESCRIPTION
    build-dms.ps1's SetDMSAssemblyInfo regenerates src/dms/Directory.Build.props with the DMS
    release version on every BuildAndPublish. The plugin contract must not be caught by that: the
    loader's newer-plugin-on-older-host preflight compares AssemblyVersions, so the contract's
    version has to move when its public surface moves and must not move when it does not. A release-
    stamped contract would refuse a plugin built against an identical surface, naming two versions
    that differ in nothing an implementer can act on.

    That the stamping writes only one path is true by construction today. This asserts it, so that a
    later edit widening the helper's reach fails a check rather than silently changing what a
    published contract version means.

    Run in two steps around a real build. Capture mode prints the two pre-build values; hand them
    back afterwards:

      ./eng/verification/Assert-PluginsVersionIndependence.ps1 -CaptureBaseline
        plugins-sha256=<hash>
        dms-version-prefix=<version, or empty when the file declares none>

      ./build-dms.ps1 BuildAndPublish -Configuration Release -DMSVersion <v> -LockedMode

      ./eng/verification/Assert-PluginsVersionIndependence.ps1 `
        -BaselinePluginsSha256 <hash> -BaselineDMSVersion <version> -ExpectedDMSVersion <v>

    The two captured values are the whole of the state that crosses the build, so they are passed as
    arguments rather than persisted. In CI the capture step appends them to $GITHUB_OUTPUT, which is
    what the key=value shape is for, and the assert step reads them back as step outputs.

    The build in the middle is the real one. Invoking the Package command instead would prove
    nothing: Package dispatches to BuildPackage alone, and only the BuildAndPublish command reaches
    Invoke-SetAssemblyInfo, so a check built on Package would pass on a run that never stamped.

.NOTES
    Two properties are asserted, and the second is what keeps the first from being vacuous.

    1. src/plugins/Directory.Build.props is byte-identical to its baseline, compared by SHA-256.
    2. src/dms/Directory.Build.props carries VersionPrefix equal to the version the build was given,
       and the baseline captured before the build did not already carry that version. Without the
       second half, a build that never stamped anything would pass property 1 trivially - which is
       the failure mode most likely to go unnoticed.

    Property 2 is read out of the props XML, not compared against a reconstruction of what the build
    script writes. Only the stamped version is this check's business; the rest of that file's content
    is the build script's own concern and is covered by the build script's own tests.

    This script does not write to the working tree, and in particular does not put
    src/dms/Directory.Build.props back the way it found it. That is the caller's job.

    The local effect is therefore that a developer who runs the sequence above is left with a
    src/dms/Directory.Build.props regenerated by the build, differing from the committed file - the
    generated one carries VersionPrefix, VersionSuffix and a Copyright element in place of the
    committed AssemblyVersion, FileVersion and InformationalVersion. That is the ordinary
    consequence of running BuildAndPublish with a -DMSVersion, not something this check introduces.
    Restore it with `git restore src/dms/Directory.Build.props` when finished, or keep it if the
    stamped metadata is what the rest of your session needs. On CI the workspace is discarded at the
    end of the job, so nothing needs restoring there.
#>
[CmdletBinding()]
param(
    # Capture mode. Run this before the build; run without it afterwards to assert.
    [switch]
    $CaptureBaseline,

    # The plugin props' SHA-256 as capture mode reported it before the build. Required when
    # asserting: the assertion has nothing to compare against without it.
    [AllowEmptyString()]
    [string]
    $BaselinePluginsSha256 = "",

    # The DMS props' VersionPrefix as capture mode reported it before the build, empty when the file
    # declared none - which is the committed state, so empty is a meaningful value and not an
    # omission.
    [AllowEmptyString()]
    [string]
    $BaselineDMSVersion = "",

    # The version passed to the build as -DMSVersion. Required when asserting: it is what the
    # positive control compares the regenerated VersionPrefix against.
    [AllowEmptyString()]
    [string]
    $ExpectedDMSVersion = "",

    [string]
    $RepositoryRoot = (Join-Path $PSScriptRoot "../..")
)

# Validated here rather than by Mandatory parameter attributes. Mandatory prompts on an interactive
# host instead of failing, which would hang a developer running this by hand, and its binder message
# cannot say why the missing value matters.

$ErrorActionPreference = "Stop"

$resolvedRoot = (Resolve-Path -LiteralPath $RepositoryRoot).ProviderPath

# The file the stamping must never reach. This is the assertion.
$pluginsPath = Join-Path $resolvedRoot "src/plugins/Directory.Build.props"
# The file the stamping does rewrite. This is the positive control.
$dmsPath = Join-Path $resolvedRoot "src/dms/Directory.Build.props"

foreach ($path in @($pluginsPath, $dmsPath)) {
    if (-not (Test-Path -LiteralPath $path)) {
        throw "Expected props file was not found: $path"
    }
}

function Get-FileSha256 {
    param([Parameter(Mandatory)][string] $Path)

    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash
}

function Get-PropsVersionPrefix {
    <#
    .SYNOPSIS
        The VersionPrefix a props file declares, or an empty string when it declares none.
    .DESCRIPTION
        The committed src/dms/Directory.Build.props carries no VersionPrefix at all - it declares
        AssemblyVersion, FileVersion and InformationalVersion instead - and the file the build
        regenerates carries VersionPrefix and none of those three. So absence is a normal pre-build
        state and is reported as an empty string rather than as an error; it is the caller that
        decides what to make of it.

        More than one VersionPrefix would make "the stamped version" ambiguous, and the build writes
        exactly one, so that is refused rather than resolved by picking a winner.
    #>
    param([Parameter(Mandatory)][string] $Path)

    try {
        $document = [xml](Get-Content -LiteralPath $Path -Raw)
    }
    catch {
        throw "Could not parse $Path as XML: $($_.Exception.Message)"
    }

    # These props files declare no XML namespace, so an unqualified path selects correctly.
    $nodes = @($document.SelectNodes("/Project/PropertyGroup/VersionPrefix"))

    if ($nodes.Count -eq 0) {
        return ""
    }

    if ($nodes.Count -gt 1) {
        throw "$Path declares $($nodes.Count) VersionPrefix elements. Exactly one is expected, and which of them is 'the stamped version' would otherwise be a guess."
    }

    return $nodes[0].InnerText.Trim()
}

if ($CaptureBaseline) {
    # key=value lines, shaped for $GITHUB_OUTPUT so CI can append them without reformatting, and
    # readable as they stand when the sequence is run by hand.
    Write-Output "plugins-sha256=$(Get-FileSha256 -Path $pluginsPath)"
    Write-Output "dms-version-prefix=$(Get-PropsVersionPrefix -Path $dmsPath)"
    return
}

if ([string]::IsNullOrWhiteSpace($ExpectedDMSVersion)) {
    throw "-ExpectedDMSVersion is required when asserting. It must be the version passed to the build as -DMSVersion; without it the positive control cannot tell a real stamping run from a build that never stamped."
}

if ([string]::IsNullOrWhiteSpace($BaselinePluginsSha256)) {
    throw "-BaselinePluginsSha256 is empty, so there is nothing to compare src/plugins/Directory.Build.props against and the assertion would pass on any tree. Pass the value capture mode printed before the build."
}

# 1. The assertion. The stamping must not have reached the plugin contract's props.
$pluginsCurrentSha256 = Get-FileSha256 -Path $pluginsPath

if ($pluginsCurrentSha256 -ne $BaselinePluginsSha256) {
    throw "src/plugins/Directory.Build.props changed during a build run with -DMSVersion $ExpectedDMSVersion (baseline $BaselinePluginsSha256, now $pluginsCurrentSha256). The plugin contract is versioned on its own public surface and must stay outside SetDMSAssemblyInfo's reach."
}

# 2. The positive control, in two halves. The verification version has to be one the tree did not
#    already carry, or a build that stamped nothing would satisfy the check below by accident.
#    Compared case-insensitively, which is the conservative direction here: two versions differing
#    only in the case of a prerelease label are too close to base a proof on.
if ($BaselineDMSVersion -ne "" -and $BaselineDMSVersion -eq $ExpectedDMSVersion) {
    throw "src/dms/Directory.Build.props already declared VersionPrefix $BaselineDMSVersion before the build, which is the version under test. A build that never stamped would pass this check unnoticed. Verify with a version the pre-build tree does not already carry."
}

$dmsCurrentVersion = Get-PropsVersionPrefix -Path $dmsPath

if ($dmsCurrentVersion -eq "") {
    throw "src/dms/Directory.Build.props declares no VersionPrefix after a build run with -DMSVersion $ExpectedDMSVersion, so this run proves nothing about version stamping. The Package command does not reach Invoke-SetAssemblyInfo; only BuildAndPublish does."
}

# -cne, not -ne. PowerShell's string comparison operators are case-insensitive by default, and a
# prerelease label that matches only when case is folded is not the version the build was given.
if ($dmsCurrentVersion -cne $ExpectedDMSVersion) {
    throw "src/dms/Directory.Build.props declares VersionPrefix $dmsCurrentVersion after a build run with -DMSVersion $ExpectedDMSVersion. Either the build did not run with that version - the Package command does not reach Invoke-SetAssemblyInfo, only BuildAndPublish does - or the stamped file was modified afterwards."
}

Write-Output "Verified src/plugins/Directory.Build.props is byte-identical ($pluginsCurrentSha256) after a build stamped to $ExpectedDMSVersion, and that src/dms/Directory.Build.props was stamped to that version having not carried it beforehand, so the check was not vacuous."
