@port = 5198


### Setup - POST Descriptors
POST http://localhost:{{port}}/data/ed-fi/educationOrganizationCategoryDescriptors

{
    "namespace": "string",
    "codeValue": "string",
    "shortDescription": "string"
}

### Setup - POST Descriptors
POST http://localhost:{{port}}/data/ed-fi/gradeLevelDescriptors

{
    "namespace": "string",
    "codeValue": "string",
    "shortDescription": "string"
}

### Setup - POST School Year 2025
POST http://localhost:{{port}}/data/ed-fi/schoolYearTypes

{
    "schoolYear": 2028,
    "currentSchoolYear": false,
    "schoolYearDescription": "Year 2025"
}

### Test GET of school years

GET http://localhost:{{port}}/data/ed-fi/schools?nameOfInstitution=School2000


###
GET http://localhost:5198/data/ed-fi/schools/7a8129e1-8b36-4b28-a624-0d448108bc83

### Setup - POST School1
POST http://localhost:{{port}}/data/ed-fi/schools

{
    "schoolId": 321,
    "nameOfInstitution": "School2100",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "string#string"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "string#string"
        }
    ],
    "classPeriods": [
        {
            "classPeriodReference": {
                "s": "b"
            }
        }
    ]
}

### POST Session1, depending on School1 and SchoolYear 2025

POST http://localhost:{{port}}/data/ed-fi/sessions

{
    "sessionName": "Session1",
    "schoolYearTypeReference": {
        "schoolYear": 1900
    },
    "beginDate": "2025-01-01",
    "endDate": "2025-12-12",
    "termDescriptor": "uri://ed-fi.org/TermDescriptor#Presentation",
    "totalInstructionalDays": 365,
    "schoolReference": {
        "schoolId": 123
    }
}

### POST a bad Session2, invalid school

POST http://localhost:{{port}}/data/ed-fi/sessions

{
    "sessionName": "Session2",
    "schoolYearTypeReference": {
        "schoolYear": 2025
    },
    "beginDate": "2025-01-01",
    "endDate": "2025-12-12",
    "termDescriptor": "uri://ed-fi.org/TermDescriptor#Presentation",
    "totalInstructionalDays": 365,
    "schoolReference": {
        "schoolId": 999
    }
}


### POST AccountabilityRating1, depending on School1 as EducationOrganization and SchoolYear 2025

POST http://localhost:{{port}}/data/ed-fi/accountabilityRatings

{
    "ratingTitle": "AccountabilityRating1",
    "rating": "Good",
    "schoolYearTypeReference": {
        "schoolYear": 2025
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 123
    }
}

### Create AccountabilityRating2 with invalid EducationOrganization, expect error

POST http://localhost:{{port}}/data/ed-fi/accountabilityRatings

{
    "ratingTitle": "AccountabilityRating1",
    "rating": "Good",
    "schoolYearTypeReference": {
        "schoolYear": 2025
    },
    "educationOrganizationReference": {
        "educationOrganizationId": 999
    }
}

### Delete School1, expect error
DELETE http://localhost:{{port}}/data/ed-fi/schools/77c9aab4-2e6e-4987-9981-1baff1ba70fb


### Create Survey referencing Session1

POST http://localhost:{{port}}/data/ed-fi/surveys

{
    "surveyIdentifier": "abc",
    "namespace": "defgh",
    "surveyTitle": "A Survey",
    "schoolYearTypeReference": {
        "schoolYear": 2025
    },
    "sessionReference": {
        "schoolId": 123,
        "schoolYear": 2025,
        "sessionName": "Session1"
    }
}

### Update Survey with invalid Session
PUT http://localhost:{{port}}/data/ed-fi/surveys/ae63728e-2f69-4609-bffd-a8179bc15d41

{
    "id": "ae63728e-2f69-4609-bffd-a8179bc15d41",
    "surveyIdentifier": "abc",
    "namespace": "defgh",
    "surveyTitle": "A Survey",
    "schoolYearTypeReference": {
        "schoolYear": 2025
    },
    "sessionReference": {
        "schoolId": 123,
        "schoolYear": 2025,
        "sessionName": "Invalid"
    }
}
