@configPort=8080
@configPort=8081
@sysAdminId=DmsConfigurationService
@sysAdminSecret=s3creT@09

### Step 1: Get a token from the config API
# @name configTokenRequest
POST http://localhost:{{configPort}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&client_id={{sysAdminId}}
&client_secret={{sysAdminSecret}}
&scope=edfi_admin_api/full_access

### Step 2: Extract the token from the response
@configToken={{configTokenRequest.response.body.access_token}}

### Step 3: Create Profile
# @name createProfile
POST http://localhost:{{configPort}}/v2/profiles/
Content-Type: application/json
Authorization: bearer {{configToken}}

{
  "ProfileName": "TestProfile_{{$randomInt 0 9999999}}",
  "Definition": "<Profile>...</Profile>"
}
### Read the newly-created profile ID from the response body
@profileId={{createProfile.response.body.id}}

### Step 4: Get All Profiles
GET http://localhost:{{configPort}}/v2/profiles/?limit=10&offset=0
Accept: application/json
Authorization: bearer {{configToken}}

### Step 5: Get Profile by Id
# @name getProfile
GET http://localhost:{{configPort}}/v2/profiles/{{profileId}}
Accept: application/json
Authorization: bearer {{configToken}}

### Step 6: Update Profile
PUT http://localhost:{{configPort}}/v2/profiles/{{profileId}}
Content-Type: application/json
Authorization: bearer {{configToken}}

{
  "Id": {{profileId}},
  "ProfileName": "UpdatedProfile_20260107",
  "Definition": "<Profile>Updated</Profile>"
}

### Step 7: Delete Profile
DELETE http://localhost:{{configPort}}/v2/profiles/{{profileId}}
Authorization: bearer {{configToken}}

### Step 8: Try to Get deleted Profile (404)
# @name getProfile
GET http://localhost:{{configPort}}/v2/profiles/{{profileId}}
Accept: application/json
Authorization: bearer {{configToken}}
