### Test POST of invalid resource

@port = 8080
#@port = 5198

POST http://localhost:{{port}}/data/ed-fi/doesNotExistDescriptor/

{
  "codeValue": "Presentation",
  "shortDescription": "Presentation",
  "description": "Presentation",
  "namespace": "uri://ed-fi.org/DoesNotExistDescriptor"
}


### Test POST of descriptor

POST http://localhost:{{port}}/data/ed-fi/contentClassDescriptors/

{
  "codeValue": "Presentation",
  "shortDescription": "Presentation",
  "description": "Presentation",
  "namespace": "uri://ed-fi.org/ContentClassDescriptor"
}

### Test GET of descriptor

GET http://localhost:{{port}}/data/ed-fi/contentClassDescriptors/a71c8b76-261b-4452-9862-7f4df0b60758

###
GET http://localhost:{{port}}/data/ed-fi/contentClassDescriptors

### Test PUT of descriptor

PUT http://localhost:{{port}}/data/ed-fi/contentClassDescriptors/a71c8b76-261b-4452-9862-7f4df0b60758

{
  "id": "a71c8b76-261b-4452-9862-7f4df0b60758",
  "codeValue": "Presentation",
  "shortDescription": "Presentation",
  "description": "1234",
  "namespace": "uri://ed-fi.org/ContentClassDescriptor"
}

### Test POST of an EducationContent

POST http://localhost:{{port}}/data/ed-fi/educationContents

{
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430"
}

### Test POST of a misspelled EducationContent

POST http://localhost:{{port}}/data/ed-fi/educationContentsss

{
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430"
}

### Test POST of an EducationContent with lousy endpoint casing

POST http://localhost:{{port}}/data/ed-fi/eDUCatiONConteNtS

{
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430"
}

### Test PUT of an EducationContent

PUT http://localhost:{{port}}/data/ed-fi/educationContents/8902c802-2b20-4481-9a27-1e92edb3834a

{
    "id": "8902c802-2b20-4481-9a27-1e92edb3834a",
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430"
}

### Test GET of an EducationContent

GET http://localhost:{{port}}/data/ed-fi/educationContents/8902c802-2b20-4481-9a27-1e92edb3834a


### Test DELETE of an EducationContent

DELETE http://localhost:{{port}}/data/ed-fi/educationContents/8902c802-2b20-4481-9a27-1e92edb3834a

### Test POST of an EducationContent with two overposted fields
POST http://localhost:{{port}}/data/ed-fi/educationContents

{
    "contentIdentifier": "933zsd4350",
    "namespace": "43210",
    "shortDescription": "abc",
    "contentClassDescriptor": "uri://ed-fi.org/ContentClassDescriptor#Presentation",
    "learningResourceMetadataURI": "21430",
    "scalarOverpost": "x",
    "objectOverpost": {
      "x": 1
    }
}

#### Test POST of a Section
POST http://localhost:{{port}}/data/ed-fi/sections

{
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z2"
            }
        }
    ]
}

#### Test POST of a Section with overposts in the classPeriods array
POST http://localhost:{{port}}/data/ed-fi/sections

{
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1",
                "scalarOverpost": "x"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z2",
                "objectOverpost": {
                    "x": 1
                }
            }
        }
    ]
}

#### Test POST of a Section with non-overpost error - missing classPeriodName in the classPeriods array
POST http://localhost:{{port}}/data/ed-fi/sections

{
    "sectionIdentifier": "c00v",
    "courseOfferingReference": {
        "localCourseCode": "abc",
        "schoolId": 666,
        "sessionName": "d",
        "schoolYear": 2034
    },
    "locationReference": {
      "classroomIdentificationCode": "1",
      "schoolId": 2
    },
    "availableCreditTypeDescriptor": "k",
    "classPeriods": [
        {
            "classPeriodReference":
            {
                "schoolId": 66,
                "classPeriodName": "z1"
            }
        },
        {
            "classPeriodReference":
            {
                "schoolId": 66
            }
        }
    ]
}


###
POST http://localhost:{{port}}/data/ed-fi/schoolYearTypes

{
    "schoolYear": 2021,
    "schoolYearDescription": "2021-2022",
    "currentSchoolYear": true
}


###
POST http://localhost:{{port}}/data/ed-fi/schoolYearTypes

{
    "schoolYear": 2022,
    "schoolYearDescription": "2022-2023",
    "currentSchoolYear": true
}


###
GET http://localhost:{{port}}/data/ed-fi/schoolYearTypes
