#5126 or 8081
@configPort=8081

#5198 or 8080
@dmsPort=8080
@sysAdminId=sys-admin
@sysAdminSecret=SdfH)98&Jk
@encodedSysAdminSecret=SdfH%2998%26Jk

#
# Create a new system administrator and create a token
#

### Create the system administrator credentials
POST http://localhost:{{configPort}}/connect/register
Content-Type: application/x-www-form-urlencoded

ClientId={{sysAdminId}}
&ClientSecret={{encodedSysAdminSecret}}
&DisplayName=System Administrator

### Create a token
# @name configTokenRequest
POST http://localhost:{{configPort}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{sysAdminId}}
&client_secret={{encodedSysAdminSecret}}
&grant_type=client_credentials
&scope=edfi_admin_api/full_access


###
@configToken={{configTokenRequest.response.body.access_token}}

#
# Create vendor, application, and new DMS client credentials
#

### Create a new vendor
# @name createVendor
POST http://localhost:{{configPort}}/v2/vendors
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "company": "Demo Vendor",
    "contactName": "George Washington",
    "contactEmailAddress": "george@example.com",
    "namespacePrefixes": "uri://ed-fi.org"
}

###
@vendorLocation={{createVendor.response.headers.location}}

### Retrieve the vendor so that we can extract the Id
# @name getVendor
GET {{vendorLocation}}
Authorization: bearer {{configToken}}

###
@vendorId={{getVendor.response.body.id}}

### Create a new application
# @name createApplication
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{vendorId}},
    "applicationName": "Demo application",
    "claimSetName": "E2E-RelationshipsWithEdOrgsOnlyClaimSet",
    "educationOrganizationIds": [6001010, 60010, 600]
}

###
@clientKey={{createApplication.response.body.key}}
@clientSecret={{createApplication.response.body.secret}}
@applicationLocation={{createApplication.response.headers.location}}

#
# DMS demonstration
#

### Read the Token URL from the Discovery API
# @name discovery
GET http://localhost:{{dmsPort}}

###
@dataApi={{discovery.response.body.urls.dataManagementApi}}

### Create a DMS token
# @name dmsTokenRequest
POST http://localhost:{{dmsPort}}/oauth/token
Authorization: basic {{clientKey}}:{{clientSecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@dmsToken={{dmsTokenRequest.response.body.access_token}}

### Create descriptor
#
POST {{dataApi}}/ed-fi/educationOrganizationCategoryDescriptors
Authorization: bearer {{dmsToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/educationOrganizationCategoryDescriptor",
    "codeValue": "XYZ",
    "shortDescription": "XYZ"
}

### Create descriptor
POST {{dataApi}}/ed-fi/localEducationAgencyCategoryDescriptors
Authorization: bearer {{dmsToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor",
    "codeValue": "ABC",
    "shortDescription": "ABC"
}

### Create State Education Agency
POST {{dataApi}}/ed-fi/stateEducationAgencies
Authorization: bearer {{dmsToken}}

{
    "stateEducationAgencyId": 400,
    "nameOfInstitution": "Hawaii Department of Education",
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/educationOrganizationCategoryDescriptor#XYZ"
        }
    ]
}

### Create State Education Agency
POST {{dataApi}}/ed-fi/stateEducationAgencies
Authorization: bearer {{dmsToken}}

{
    "stateEducationAgencyId": 600,
    "nameOfInstitution": "California Department of Education",
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/educationOrganizationCategoryDescriptor#XYZ"
        }
    ]
}

### Create Local Education Agency
# @name createLEA
POST {{dataApi}}/ed-fi/localEducationAgencies
Authorization: bearer {{dmsToken}}

{
    "localEducationAgencyId": 60010,
    "nameOfInstitution": "LA Public Schools",
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/educationOrganizationCategoryDescriptor#XYZ"
        }
    ],
    "stateEducationAgencyReference": {
        "stateEducationAgencyId": 600
    },
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor#ABC"
}

###
@leaLocation={{createLEA.response.headers.location}}

# @name getLEA
GET {{leaLocation}}
Authorization: bearer {{dmsToken}}

### Update LEA - change parent SEA
# @name putLEA
PUT {{leaLocation}}
Authorization: bearer {{dmsToken}}

{
    "id": "{{getLEA.response.body.id}}",
    "localEducationAgencyId": 60010,
    "nameOfInstitution": "LA Public Schools",
    "categories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/educationOrganizationCategoryDescriptor#XYZ"
        }
    ],
    "stateEducationAgencyReference": {
        "stateEducationAgencyId": 400
    },
    "localEducationAgencyCategoryDescriptor": "uri://ed-fi.org/localEducationAgencyCategoryDescriptor#ABC"
}

### Create descriptor
POST {{dataApi}}/ed-fi/gradeLevelDescriptors
Authorization: bearer {{dmsToken}}
Content-Type: application/json

{
    "namespace": "uri://ed-fi.org/gradeLevelDescriptor",
    "codeValue": "Tenth Grade",
    "shortDescription": "Tenth Grade"
}

### Create School
# @name createSchool
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{dmsToken}}

{
    "schoolId": 6001010,
    "nameOfInstitution": "Bayside High School",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/educationOrganizationCategoryDescriptor#XYZ"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/gradeLevelDescriptor#Tenth Grade"
        }
    ],
    "localEducationAgencyReference": {
        "localEducationAgencyId": 60010
    }
}

###
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{dmsToken}}

{
    "schoolReference": {
        "schoolId": 6001010
    },
    "beginDate": "2023-08-01",
    "endDate": "2023-08-07",
    "totalInstructionalDays": 5,
    "weekIdentifier": "ABCDE"
}

###
GET {{dataApi}}/ed-fi/academicWeeks?weekIdentifier=ABCDE
Authorization: bearer {{dmsToken}}

### Create a new application
# @name createApplication2
POST http://localhost:{{configPort}}/v2/applications
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "vendorId": {{vendorId}},
    "applicationName": "Demo application 22",
    "claimSetName": "E2E-RelationshipsWithEdOrgsOnlyClaimSet",
    "educationOrganizationIds": [123456]
}

###
@client2Key={{createApplication2.response.body.key}}
@client2Secret={{createApplication2.response.body.secret}}
@application2Location={{createApplication2.response.headers.location}}

### Create a DMS token
# @name dmsTokenRequest2
POST http://localhost:{{dmsPort}}/oauth/token
Authorization: basic {{client2Key}}:{{client2Secret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials

###
@dmsToken2={{dmsTokenRequest2.response.body.access_token}}

### Create School
# @name createSchool
POST {{dataApi}}/ed-fi/schools
Authorization: bearer {{dmsToken2}}

{
    "schoolId": 123456,
    "nameOfInstitution": "Westside High School",
    "educationOrganizationCategories": [
        {
            "educationOrganizationCategoryDescriptor": "uri://ed-fi.org/educationOrganizationCategoryDescriptor#XYZ"
        }
    ],
    "gradeLevels": [
        {
            "gradeLevelDescriptor": "uri://ed-fi.org/gradeLevelDescriptor#Tenth Grade"
        }
    ]
}

###
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{dmsToken2}}

{
    "schoolReference": {
        "schoolId": 123456
    },
    "beginDate": "2023-08-01",
    "endDate": "2023-08-07",
    "totalInstructionalDays": 5,
    "weekIdentifier": "FGHIJ"
}

### Should return the academic week just created
GET {{dataApi}}/ed-fi/academicWeeks?weekIdentifier=FGHIJ
Authorization: bearer {{dmsToken2}}

### Should return [] this token does not have access to 6001010
GET {{dataApi}}/ed-fi/academicWeeks?weekIdentifier=ABCDE
Authorization: bearer {{dmsToken2}}

###
POST {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{dmsToken2}}

{
    "schoolReference": {
        "schoolId": 123456
    },
    "beginDate": "2023-08-01",
    "endDate": "2023-08-07",
    "totalInstructionalDays": 5,
    "weekIdentifier": "ABCDE"
}

### Should return two academic weeks
GET {{dataApi}}/ed-fi/academicWeeks
Authorization: bearer {{dmsToken2}}
