# This file tests the /v2/dataStoreContexts endpoints.
@dmsPort=8080
@configPort=8081

@sysAdminId=DmsConfigurationService
@sysAdminSecret=ValidClientSecret1234567890!Abcd

### Create a Configuration Service token
# @name configTokenRequest
POST http://localhost:{{configPort}}/connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{sysAdminId}}
&client_secret={{sysAdminSecret}}
&grant_type=client_credentials
&scope=edfi_admin_api/full_access

### Read the token from the response body
@configToken={{configTokenRequest.response.body.access_token}}

### Create a new dataStore
# @name createDataStore
POST http://localhost:{{configPort}}/v2/dataStores
Content-Type: application/json
Authorization: bearer {{configToken}}

{
    "dataStoreType": "Production",
    "name": "Test Instance",
    "connectionString": "host=dms-postgresql;port=5432;username=postgres;password=abcdefgh1!;database=edfi_datamanagementservice;"
}

### Read the newly-created DataStore ID from the response body
@dataStoreId={{createDataStore.response.body.id}}

### Create a new data store context
# @name createDataStoreContext
POST http://localhost:{{configPort}}/v2/dataStoreContexts
Content-Type: application/json
Authorization: bearer {{configToken}}

{
  "dataStoreId": {{dataStoreId}},
  "contextKey": "schoolYear",
  "contextValue": "2022"
}

### Read the newly-created DataStore Context ID from the response body
@dataStoreContextId={{createDataStoreContext.response.body.id}}

### List all data store contexts
GET http://localhost:{{configPort}}/v2/dataStoreContexts
Authorization: bearer {{configToken}}

### Get data store context by ID
GET http://localhost:{{configPort}}/v2/dataStoreContexts/{{dataStoreContextId}}
Authorization: bearer {{configToken}}

### Update data store context by ID
PUT http://localhost:{{configPort}}/v2/dataStoreContexts/{{dataStoreContextId}}
Content-Type: application/json
Authorization: bearer {{configToken}}

{
  "id": {{dataStoreContextId}},
  "dataStoreId": {{dataStoreId}},
  "contextKey": "schoolYear",
  "contextValue": "2023"
}

### Delete data store context by ID
DELETE http://localhost:{{configPort}}/v2/dataStoreContexts/{{dataStoreContextId}}
Authorization: bearer {{configToken}}

### Get data store context by ID should return 404.
GET http://localhost:{{configPort}}/v2/dataStoreContexts/{{dataStoreContextId}}
Authorization: bearer {{configToken}}
