# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

#Requires -Version 7

# Regression cover for Assert-PluginsVersionIndependence.ps1.
#
# Two properties are pinned here, and the second is the one that keeps the first honest.
#
# The check must fail when src/plugins/Directory.Build.props moved during a stamping build - that is
# the whole point of it - and it must also fail when no stamping happened at all, because otherwise
# the plugin-side assertion passes trivially on a run that proves nothing.
#
# The stamped fixtures below carry a VersionPrefix and nothing else of interest. They deliberately do
# not reproduce what SetDMSAssemblyInfo writes: the verifier reads only the version out of that file,
# so a second copy of the build script's template here would pin behaviour neither side has.
#
# Every fixture is a purpose-created repository under the temp directory, passed via -RepositoryRoot.
# Nothing here writes into the working tree, and nothing here reads from it either - see
# New-FixtureRepository for why the second half matters as much as the first.

BeforeAll {
    $script:verifier = [System.IO.Path]::GetFullPath(
        (Join-Path $PSScriptRoot "../Assert-PluginsVersionIndependence.ps1")
    )
    $script:fixtureRoot = Join-Path ([System.IO.Path]::GetTempPath()) "dms1496-versioncheck-tests-$([guid]::NewGuid().ToString('N'))"
    New-Item -ItemType Directory -Path $script:fixtureRoot -Force | Out-Null

    # A fixture's props files are written from the literals below rather than copied out of the
    # working tree, and that is not a stylistic choice.
    #
    # The CI lane runs this suite in the same workspace as, and after, the BuildAndPublish that
    # stamps src/dms/Directory.Build.props - the verifier no longer restores it, deliberately,
    # because the `dotnet pack --no-build` steps in between need the stamped metadata. So by the
    # time Pester runs, the working-tree DMS props already declares a VersionPrefix. A fixture
    # copied from it would carry that version, and the not-stamped case below would silently stop
    # being a not-stamped case: it would get the wrong-version diagnostic instead of the missing-
    # VersionPrefix one and fail the lane.
    #
    # The plugin-side literal is fixed here for the same reason in the other direction - the
    # fixtures edit it by name, so the contract's real version bumping must not decide whether a
    # test exercises anything.
    #
    # Both are the shape of their committed counterparts reduced to what the verifier reads: the
    # DMS one carries no VersionPrefix, which is the pre-build state, and the plugin one carries a
    # VersionPrefix that must never move.
    function New-FixtureRepository {
        [CmdletBinding(SupportsShouldProcess)]
        param([Parameter(Mandatory)][string] $Name)

        $root = Join-Path $script:fixtureRoot "$Name-$([guid]::NewGuid().ToString('N'))"

        $pluginsProps = @"
<Project>
    <PropertyGroup>
        <VersionPrefix>1.0.0</VersionPrefix>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <Product>Ed-Fi API</Product>
    </PropertyGroup>
</Project>
"@

        $dmsProps = @"
<Project>
    <PropertyGroup>
        <AssemblyVersion>8.0.0</AssemblyVersion>
        <FileVersion>8.0.0</FileVersion>
        <InformationalVersion>8.0.0</InformationalVersion>
        <Product>Ed-Fi API</Product>
    </PropertyGroup>
</Project>
"@

        if ($PSCmdlet.ShouldProcess($root, "Create fixture repository")) {
            New-Item -ItemType Directory -Path (Join-Path $root "src/plugins") -Force | Out-Null
            New-Item -ItemType Directory -Path (Join-Path $root "src/dms") -Force | Out-Null

            Set-Content -LiteralPath (Join-Path $root "src/plugins/Directory.Build.props") `
                -Value $pluginsProps -NoNewline
            Set-Content -LiteralPath (Join-Path $root "src/dms/Directory.Build.props") `
                -Value $dmsProps -NoNewline
        }

        return $root
    }

    # Stands in for what a stamping build leaves behind, reduced to the one element the verifier
    # reads. Everything else SetDMSAssemblyInfo writes is that script's business, not this check's.
    function Set-StampedDmsPropsContent {
        [CmdletBinding(SupportsShouldProcess)]
        param(
            [Parameter(Mandatory)][string] $Root,
            [Parameter(Mandatory)][string] $Version
        )

        $path = Join-Path $Root "src/dms/Directory.Build.props"

        $content = @"
<Project>
    <!-- This file is generated by the build script. -->
    <PropertyGroup>
        <VersionPrefix>$Version</VersionPrefix>
        <VersionSuffix></VersionSuffix>
    </PropertyGroup>
</Project>
"@

        if ($PSCmdlet.ShouldProcess($path, "Write stamped props")) {
            Set-Content -LiteralPath $path -Value $content -NoNewline
        }
    }

    function Invoke-Check {
        param(
            [Parameter(Mandatory)][string] $Root,
            [Parameter(Mandatory)][hashtable] $Baseline,
            [string] $ExpectedDMSVersion
        )

        $threw = $false
        $message = ""

        try {
            $arguments = @{
                BaselinePluginsSha256 = $Baseline["plugins-sha256"]
                BaselineDMSVersion    = $Baseline["dms-version-prefix"]
                RepositoryRoot        = $Root
            }
            if (-not [string]::IsNullOrWhiteSpace($ExpectedDMSVersion)) {
                $arguments.ExpectedDMSVersion = $ExpectedDMSVersion
            }

            & $script:verifier @arguments | Out-Null
        }
        catch {
            $threw = $true
            $message = $_.Exception.Message
        }

        return [pscustomobject]@{
            Threw   = $threw
            Message = $message
        }
    }

    # Capture mode's real output, parsed the way the CI step's $GITHUB_OUTPUT consumer would read it
    # back. Going through the script rather than computing the two values here is what keeps a
    # capture-side regression - a renamed key, a hash over the wrong file - visible to these tests.
    function Get-Baseline {
        param([Parameter(Mandatory)][string] $Root)

        $captured = @{}

        foreach ($line in @(& $script:verifier -CaptureBaseline -RepositoryRoot $Root)) {
            $split = "$line".Split("=", 2)
            $captured[$split[0]] = $split[1]
        }

        $captured.Keys | Sort-Object |
            Should -Be @("dms-version-prefix", "plugins-sha256") -Because "the assert step reads these two step outputs by name"

        return $captured
    }
}

AfterAll {
    if ($script:fixtureRoot -and (Test-Path -LiteralPath $script:fixtureRoot)) {
        Remove-Item -LiteralPath $script:fixtureRoot -Recurse -Force
    }
}

Describe "Assert-PluginsVersionIndependence" {

    Context "A genuine stamping run" {

        It "accepts a run that stamped the DMS props and left the plugin contract's props alone" {
            $root = New-FixtureRepository -Name "happy-path"
            $baseline = Get-Baseline -Root $root
            $dmsProps = Join-Path $root "src/dms/Directory.Build.props"
            $pluginsProps = Join-Path $root "src/plugins/Directory.Build.props"

            Set-StampedDmsPropsContent -Root $root -Version "9.9.9"
            $stamped = Get-Content -LiteralPath $dmsProps -Raw
            $pluginsContent = Get-Content -LiteralPath $pluginsProps -Raw

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeFalse -Because $result.Message

            # The check verifies; it does not tidy up. A caller who wants the committed file back
            # restores it themselves, and a caller mid-way through a packaging sequence needs the
            # stamped metadata still in place.
            Get-Content -LiteralPath $dmsProps -Raw |
                Should -BeExactly $stamped -Because "the check no longer restores the stamped file"
            Get-Content -LiteralPath $pluginsProps -Raw | Should -BeExactly $pluginsContent
        }
    }

    Context "The plugin contract's props must not move" {

        It "fails when the stamping reached the plugin contract's props" {
            # The defect the whole check exists to catch, with the DMS side genuinely stamped so the
            # failure can only be about the plugin contract.
            $root = New-FixtureRepository -Name "plugins-stamped"
            $pluginsProps = Join-Path $root "src/plugins/Directory.Build.props"
            $baseline = Get-Baseline -Root $root

            Set-StampedDmsPropsContent -Root $root -Version "9.9.9"
            (Get-Content -LiteralPath $pluginsProps -Raw) -replace
                "<VersionPrefix>1.0.0</VersionPrefix>", "<VersionPrefix>9.9.9</VersionPrefix>" |
                Set-Content -LiteralPath $pluginsProps -NoNewline

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*must stay outside SetDMSAssemblyInfo's reach*"
        }

        It "fails on any change to the plugin contract's props, not only a version change" {
            # SHA-256 over the whole file, so a widened stamping helper that rewrote the file
            # wholesale is caught even if it happened to leave VersionPrefix alone.
            $root = New-FixtureRepository -Name "plugins-edited"
            $pluginsProps = Join-Path $root "src/plugins/Directory.Build.props"
            $baseline = Get-Baseline -Root $root

            Set-StampedDmsPropsContent -Root $root -Version "9.9.9"
            (Get-Content -LiteralPath $pluginsProps -Raw) -replace
                "<Product>Ed-Fi API</Product>", "<Product>Ed-Fi API </Product>" |
                Set-Content -LiteralPath $pluginsProps -NoNewline

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*must stay outside SetDMSAssemblyInfo's reach*"
        }
    }

    Context "The check cannot pass vacuously" {

        It "fails when no stamping run happened between capture and assert" {
            $root = New-FixtureRepository -Name "no-stamping"
            $baseline = Get-Baseline -Root $root

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*declares no VersionPrefix*"
        }

        It "fails when the DMS props was stamped to some other version" {
            $root = New-FixtureRepository -Name "wrong-version"
            $baseline = Get-Baseline -Root $root

            Set-StampedDmsPropsContent -Root $root -Version "1.2.3"

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*declares VersionPrefix 1.2.3*"
        }

        It "fails when the stamped version matches only once case is folded" {
            # PowerShell's -eq on strings is case-insensitive, so a comparison written with -ne would
            # accept a prerelease label the build was never given.
            $root = New-FixtureRepository -Name "case-only-version"
            $baseline = Get-Baseline -Root $root

            Set-StampedDmsPropsContent -Root $root -Version "9.9.9-PRE.1"

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9-pre.1"

            $result.Threw | Should -BeTrue
            # -BeLikeExactly: Should -BeLike folds case, and case is the entire difference here.
            $result.Message | Should -BeLikeExactly "*declares VersionPrefix 9.9.9-PRE.1*"
        }

        It "refuses a verification version the pre-build tree already carried" {
            # Without this guard a build that stamped nothing satisfies the positive control by
            # accident, and the plugin-side assertion it is supposed to underwrite means nothing.
            $root = New-FixtureRepository -Name "already-at-version"
            Set-StampedDmsPropsContent -Root $root -Version "9.9.9"
            $baseline = Get-Baseline -Root $root

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*already declared VersionPrefix 9.9.9 before the build*"
        }

        It "requires the expected version, without which the positive control cannot fire" {
            $root = New-FixtureRepository -Name "missing-version"
            $baseline = Get-Baseline -Root $root

            $result = Invoke-Check -Root $root -Baseline $baseline

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*-ExpectedDMSVersion is required*"
        }
    }

    Context "Baseline inputs" {

        It "refuses an empty plugin props hash rather than comparing against nothing" {
            # The one way the two captured values can arrive wrong now that they are arguments: a
            # step output that never got written resolves to an empty string, and an equality test
            # against it would pass on any tree at all.
            $root = New-FixtureRepository -Name "empty-baseline-hash"
            $baseline = Get-Baseline -Root $root
            $baseline["plugins-sha256"] = ""

            Set-StampedDmsPropsContent -Root $root -Version "9.9.9"

            $result = Invoke-Check -Root $root -Baseline $baseline -ExpectedDMSVersion "9.9.9"

            $result.Threw | Should -BeTrue
            $result.Message | Should -BeLike "*-BaselinePluginsSha256 is empty*"
        }
    }
}
