# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

#Requires -Version 7

<#
.SYNOPSIS
    Writes the environment file the Instance Management identity plugin slice runs against.

.DESCRIPTION
    Copies eng/docker-compose/.env.routeContext.e2e and appends the plugin deployment settings: the
    compose files that mount a plugin root and allow the identity fixture, the absolute host path of
    the plugin root, and the allowlist. The result is generated per run and never committed, so a
    change to the route-context environment file cannot be forgotten in a second copy.

    The plugin root is the directory that holds the Acme.IdentityFixture directory, such as the
    PackedContractPluginFixtures stage under the integration test project's bin directory. The script
    fails before writing anything when Acme.IdentityFixture/Acme.IdentityFixture.dll is not there.

    Prints the path of the written file.

.PARAMETER PluginRoot
    The directory that holds Acme.IdentityFixture/Acme.IdentityFixture.dll.

.PARAMETER Destination
    Where to write the environment file. Defaults to eng/docker-compose/.derived/identity-plugin.env,
    which is gitignored.

.EXAMPLE
    $envFile = ./New-IdentityPluginEnvironmentFile.ps1 -PluginRoot ./src/dms/tests/EdFi.DataManagementService.Tests.Integration/bin/Release/net10.0/PackedContractPluginFixtures
    ./build-dms.ps1 InstanceE2ETest -Configuration Release -EnvironmentFile $envFile -TestFilter 'Category=@instance-management-identity-plugin'
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $PluginRoot,

    [string] $Destination
)

$ErrorActionPreference = "Stop"

$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "../../../..")).Path
$composeRoot = Join-Path $repositoryRoot "eng/docker-compose"
$pluginName = "Acme.IdentityFixture"

if (-not (Test-Path -LiteralPath $PluginRoot -PathType Container)) {
    throw "The plugin root '$PluginRoot' does not exist. It must be the directory that holds $pluginName/$pluginName.dll."
}

$pluginRootFull = (Resolve-Path -LiteralPath $PluginRoot).Path
$fixtureDll = Join-Path $pluginRootFull "$pluginName/$pluginName.dll"

if (-not (Test-Path -LiteralPath $fixtureDll -PathType Leaf)) {
    throw "The identity fixture is not staged: '$fixtureDll' does not exist. Build the integration test project in Release so it stages the packed contract fixtures, or point -PluginRoot at the extracted PackedContractPluginFixtures directory."
}

if ([string]::IsNullOrWhiteSpace($Destination)) {
    $Destination = Join-Path $composeRoot ".derived/identity-plugin.env"
}

$source = Join-Path $composeRoot ".env.routeContext.e2e"
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Generated by New-IdentityPluginEnvironmentFile.ps1 from .env.routeContext.e2e. Do not edit; regenerate.")

foreach ($line in Get-Content -LiteralPath $source) {
    $lines.Add($line)
}

$lines.Add("")
$lines.Add("# Identity plugin slice: mount the plugin root, allow the fixture, and give it its configuration.")
$lines.Add("DMS_PLUGINS_COMPOSE_FILES=plugins-dms.yml;tests/plugin-deployment/plugins-allowed-dms.yml;tests/identity-plugin/identity-fixture-dms.yml")
$lines.Add("DMS_PLUGINS_MOUNT_SOURCE=$pluginRootFull")
$lines.Add("DMS_PLUGINS_ALLOWED=$pluginName")

$destinationDirectory = Split-Path -Parent ([System.IO.Path]::GetFullPath($Destination))
New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null

Set-Content -LiteralPath $Destination -Value $lines -Encoding utf8

return (Resolve-Path -LiteralPath $Destination).Path
