apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serviceName: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      serviceName: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        serviceName: postgres
    spec:
      containers:
      - name: postgres-db
        image: postgres:16.2-alpine3.19@sha256:b89a4e92591810eac1fbce6107485d7c6b9449df51c1ccfcfed514a7fdd69955
        ports:
            - containerPort: 80
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: postgres-password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: postgres-host
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: app-configmap
                key: postgres-port
        resources: {}
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: pgsql-data
      restartPolicy: Always
      volumes:
        - name: pgsql-data
          persistentVolumeClaim:
            claimName: pgsql-data
status: {}
