apiVersion: v1
kind: Service
metadata:
  labels:
    serviceName: data-management-service
  name: data-management-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    serviceName: data-management-service
status:
  loadBalancer: {}
