# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: EdFi.Dms.Minimal.Template.PostgreSQL
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  STANDARD_REFERENCE: "v5.2.0"
  PACKAGE_NAME: EdFi.Dms.Minimal.Template.PostgreSQL"
  ARTIFACTS_FEED_URL: "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json"
  ARTIFACTS_API_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/ed-fi-alliance/Ed-Fi-Alliance-OSS/_packaging/EdFi/nuget/v3/index.json","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'

permissions: read-all

jobs:
  build-template:
    name: Build template package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Checkout Ed-Fi-Data-Standard
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
            repository: Ed-Fi-Alliance-OSS/Ed-Fi-Data-Standard
            path: Ed-Fi-Data-Standard/
            ref: ${{ env.STANDARD_REFERENCE }}

      - name: Set Version Numbers
        id: versions
        run: |
          Import-Module ./package-helpers.psm1
          Get-VersionNumber -projectPrefix "dms" # Match the DMS version

      - name: Start DMS Docker
        run: |
          ./start-local-dms.ps1 -EnvironmentFile "./.env.e2e" -SearchEngine "OpenSearch" -enableConfig
        working-directory: eng/docker-compose/

      - name: Generate Minimal Template package
        run: |
          $packageVersion = "${{ steps.versions.outputs.dms-semver }}" -replace "dms-v", ""

          ./Invoke-BuildMinimalTemplate.ps1 -SampleDataDirectory "${{ github.workspace }}/Ed-Fi-Data-Standard/Descriptors" -Extension "ed-fi" -PackageVersion $packageVersion
        working-directory: eng/DatabaseTemplates/

      - name: Upload Minimal Template Package as Artifact
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: "${{ env.PACKAGE_NAME }}-NuGet"
          path: ${{ github.workspace }}/eng/DatabaseTemplates/MinimalTemplate/*.nupkg
          if-no-files-found: error
          retention-days: 30

  publish-template-package:
    name: Publish Minimal Template Package
    needs: build-template
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get Minimal Template Package Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 #v4.1.8
        with:
          name: ${{ env.PACKAGE_NAME }}-NuGet

      - name: Install-credential-handler DMS
        run: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"

      - name: Push Minimal Template Package to Azure Artifacts
        run: |
         $artifact = (Get-ChildItem -Path $_ -Name -Include *.nupkg)
         $arguments = @{
           EdFiNuGetFeed = "${{ env.ARTIFACTS_FEED_URL }}"
           NuGetApiKey = "${{ env.ARTIFACTS_API_KEY }}"
         }

         $artifact | ForEach-Object {
             $arguments.PackageFile = $_
             ./build-dms.ps1 Push @arguments
          }
