# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On DMS Pull Request

on:
  push:
    # Running on push to main to support CodeQL on C#
    branches:
      - main
    paths:
      - "src/dms/**/*.cs"
      - "src/dms/**/*.csproj"
      - "src/dms/**/*.sql"
      - "src/**/Directory.Packages.props"
      - "src/dms/**/*.feature"
  pull_request:
    branches:
      - main
    paths:
      - "src/dms/**/*.cs"
      - "src/dms/**/*.csproj"
      - "src/dms/**/*.sql"
      - ".github/**/*dms*.yml"
      - "src/**/Directory.Packages.props"
      - "src/dms/**/*.feature"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  scan-actions-bidi:
    name: Scan Actions, scan all files for BIDI Trojan Attacks
    uses: Ed-Fi-Alliance-OSS/Ed-Fi-Actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-config.json

  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: ./build-dms.ps1 Build -Configuration Release

      - name: Install Coverlet Reference
        if: success()
        run: |
          dotnet tool install --global coverlet.console
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Run Unit Tests
        run: ./build-dms.ps1 UnitTest -Configuration Release

      - name: Generate Coverage Report
        if: ${{ hashFiles('coverage.cobertura.xml') != '' }}
        run: ./build-dms.ps1 Coverage

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
        with:
          name: Coverage Report
          path: coveragereport

      - name: Upload Test Results
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: (success() || failure())
        with:
          name: Unit Tests
          path: '**/*.trx'
          path-replace-backslashes: 'true'
          reporter: dotnet-trx

  run-integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
    defaults:
      run:
        shell: pwsh
    services:
      postgres:
        image: postgres:16.3-alpine
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: ./build-dms.ps1 Build -Configuration Release

      - name: Run Integration Tests
        if: success()
        run: ./build-dms.ps1 IntegrationTest -Configuration Release

      - name: Upload Integration Test Results
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: (success() || failure())
        with:
          name: Integration Tests
          path: '**/*.trx'
          path-replace-backslashes: 'true'
          reporter: dotnet-trx

  run-e2e-tests:
    name: Run E2E Tests
    needs: run-unit-tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@87b7050bc53ea08284295505d98d2aa94301e852 # v4.2
        with:
          dotnet-version: '8.0.x'

      - name: Build
        run: ./build-dms.ps1 Build -Configuration Release

      - name: Run OpenSearch End to End Tests
        if: success()
        run: ./build-dms.ps1 E2ETest -EnableOpenSearch  -Configuration Release

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
        with:
          name: test-logs
          path: |
            ./src/services/EdFi.DataManagementService.Api.Tests.E2E/bin/Release/net8.0/logs
          retention-days: 10

      - name: Upload Test Results
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        if: (success() || failure())
        with:
          name: E2E Test Results
          path: '**/*.trx'
          path-replace-backslashes: 'true'
          reporter: dotnet-trx

      - name: Download OpenAPI specs
        run: |
          mkdir specs
          Invoke-WebRequest -Uri "http://localhost:8080/metadata/specifications/resources-spec.json" -OutFile "specs/resources-spec.json"
          Invoke-WebRequest -Uri "http://localhost:8080/metadata/specifications/descriptors-spec.json" -OutFile "specs/descriptors-spec.json"
          Invoke-WebRequest -Uri "http://localhost:8080/metadata/specifications/discovery-spec.json" -OutFile "specs/discovery-spec.json"

      - name: Validate Resources Spec
        uses: swaggerexpert/swagger-editor-validate@54b85e2f5c1fcdee85308dd57cad8c8ec19d3970
        with:
          definition-file: specs/resources-spec.json
        continue-on-error: true

      - name: Validate Descriptors Spec
        uses: swaggerexpert/swagger-editor-validate@54b85e2f5c1fcdee85308dd57cad8c8ec19d3970
        with:
          definition-file: specs/descriptors-spec.json
        continue-on-error: true

      - name: Validate Discovery Spec
        uses: swaggerexpert/swagger-editor-validate@54b85e2f5c1fcdee85308dd57cad8c8ec19d3970
        with:
          definition-file: specs/discovery-spec.json
        continue-on-error: true

  event_file:
    name: Upload Event File
    runs-on: ubuntu-latest
    needs: [run-unit-tests, run-e2e-tests, run-integration-tests]
    if: always()
    steps:
    - name: Upload
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5
      with:
        name: Event File
        path: ${{ github.event_path }}
